### ISSUE TITLE
Setting apiBuilderCLIConfigDirectory doesn't have any effect

### ISSUE THREAD

**Issue by jkenny** [sirocchj/sbt-api-builder#16]

**Comment by sirocchj** [comment]
Thanks for reporting @jkenny !

The issue you're experiencing is due to lack of documentation, I fear.

That setting is scoped at _Compile_ and _Test_ configurations, hence the following will unblock your usecase:
```sbtshell
Compile / apiBuilderCLIConfigDirectory := baseDirectory.value / ".apibuilder" // my config is at base_path/.apibuilder
```

**Comment by jkenny** [comment]
I thought it would fall back to the Global configuration if no specific configuration was selected. I guess it's because you set fallbacks explicitly [here](https://github.com/sirocchj/sbt-api-builder/blob/61406a1b91aaa70686a21f7d89183512324a1f2b/src/main/scala/apibuilder/sbt/ApiBuilderPlugin.scala#L46)?

**Comment by sirocchj** [comment]
It normally would fallback to delegates, see `inspect apiBuilderCLIConfigDirectory` in an `sbt` shell and [here](https://www.scala-sbt.org/1.0/docs/Scope-Delegation.html)
However, in the code you linked I'm actually explicitly scoping that key to the value of `Compile/sourceDirectory` and `Test/sourceDirectory` (`src/main` and `src/test`, respectively). Hence to override those you need to scope them at same level at least

**Comment by jkenny** [comment]
Makes sense. Thanks!

**Comment by jkenny** [comment]
I see you updated the docs. Thanks :)
