### ISSUE TITLE
Accept api-builder token value from environment variable

### ISSUE THREAD

**Issue by amarrella** [sirocchj/sbt-api-builder#20]
This would make CI life easier, since for now I have to do the following steps which is not ideal
```
- mkdir -p ~/.apibuilder
- touch ~/.apibuilder/config
- echo "[default]" >> ~/.apibuilder/config
- echo "token = $(echo $APIBUILDER_TOKEN)" >> ~/.apibuilder/config
```

**Comment by sirocchj** [comment]
Maybe badly documented but... https://github.com/sirocchj/sbt-api-builder/blob/master/src/main/scala/apibuilder/sbt/ApiBuilderPlugin.scala (I’d gladly accept a pr for fixing the README!)
Addressed by @plippe in #6 or am I missing something?

**Comment by amarrella** [comment]
Sorry, it's documented clearly already :D i just missed it

**Comment by plippe** [comment]
Yep, go back in your box :D

**Comment by amarrella** [comment]
https://media.giphy.com/media/bHxyZJdcVMZUI/giphy.gif
